---
application:
  name: "catalog"
  project: "Catalog"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "catalog"
  version: "11"
routers:
- name: "main-catalog"
  routes:
  - application_name: "catalog"
    paths:
    - "/*"
